# Generated by Django 6.0 on 2026-01-05 05:19

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_image', models.ImageField(upload_to='temp/apply/%Y/%m/', verbose_name='证书临时文件')),
                ('cert_no', models.CharField(max_length=100, verbose_name='申请证书编号')),
                ('payload', models.JSONField(verbose_name='申请详情数据')),
                ('status', django_fsm.FSMField(default='pending', max_length=50, verbose_name='审批状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
