# Generated by Django 6.0 on 2026-01-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardapplication',
            name='award_date',
            field=models.DateField(default="2026-01-01", verbose_name='获奖日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='awardapplication',
            name='award_level',
            field=models.CharField(default="三等奖", max_length=50, verbose_name='获奖等级'),
            preserve_default=False,
        ),
    ]
