# Generated by Django 4.2.27 on 2026-01-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_awardapplication_award_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardapplication',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
