# Generated by Django 4.2.27 on 2026-01-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_alter_awardapplication_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardapplication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
