# Generated by Django 6.0 on 2025-12-28 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificate', '0001_initial'),
        ('competitions', '0002_competition_uri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_level', models.CharField(max_length=50, verbose_name='获奖等级')),
                ('award_date', models.DateField(verbose_name='获奖日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award', to='certificate.certificate', verbose_name='获奖证书')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='competitions.competition', verbose_name='所属竞赛')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_awards', to=settings.AUTH_USER_MODEL, verbose_name='录入人')),
                ('instructors', models.ManyToManyField(related_name='teacher_awards', to=settings.AUTH_USER_MODEL, verbose_name='指导老师')),
                ('participants', models.ManyToManyField(related_name='student_awards', to=settings.AUTH_USER_MODEL, verbose_name='参赛学生')),
            ],
            options={
                'verbose_name': '获奖信息',
                'db_table': 'sys_award',
                'ordering': ['-award_date'],
            },
        ),
    ]
