# Generated by Django 4.2.27 on 2026-01-06 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_alter_competition_id_alter_competitioncategory_id_and_more'),
        ('award', '0002_alter_award_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='competitions.competitionevent', verbose_name='所属赛事场次'),
        ),
        migrations.AlterField(
            model_name='award',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
