# Generated by Django 4.2.27 on 2026-01-11 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('award', '0003_award_event_alter_award_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardImportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('correcting', '待修正'), ('finished', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('file_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AwardImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_competition', models.CharField(blank=True, max_length=255)),
                ('raw_participants', models.TextField(blank=True)),
                ('raw_instructors', models.TextField(blank=True)),
                ('award_level', models.CharField(blank=True, max_length=50)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('cert_no', models.CharField(blank=True, max_length=100)),
                ('is_valid', models.BooleanField(default=False)),
                ('error_msg', models.TextField(blank=True)),
                ('competition_analysis', models.JSONField(default=dict)),
                ('participants_analysis', models.JSONField(default=list)),
                ('instructors_analysis', models.JSONField(default=list)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='award.awardimporttask')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
