# Generated by Django 4.2.27 on 2026-01-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0004_awardimporttask_awardimportitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardimporttask',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
