services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: my_project_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  frontend:
    build: ../frontend # 指向前端项目的目录
    container_name: pure-admin-web
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network

  web:
    build: .
    # 修改启动命令，使用 uwsgi 启动
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py init_project &&
             uwsgi --ini uwsgi.ini"
    volumes:
      - .:/app
      - ./media:/app/media
      - ./static:/app/static # 挂载的静态资源
    networks:
      - app-network
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0  # 切换到 uWSGI 通常意味着进入非开发模式
      - DB_HOST=db
      - DB_NAME=my_project_db
      - DB_USER=user
      - DB_PASSWORD=password123
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery:
    build: .
    command: celery -A competitionManagementSys worker -l info -P eventlet
    volumes:
      - .:/app
      - ./media:/app/media # Celery 如果处理文件也需要挂载
    environment:
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy

      redis:
        condition: service_healthy
    networks:
      - app-network

volumes:
  mysql_data:
  redis_data:

networks:
  app-network:
    driver: bridge