[uwsgi]
# 指向你的项目目录
chdir           = /app
# 导入 Django 的 wsgi 模块
module          = competitionManagementSys.wsgi:application
# 监听端口
http            = :8000

# 进程管理
master          = true
processes       = 4
threads         = 2
vacuum          = true

# 静态资源处理（如果生产环境不使用 Nginx，则由 uwsgi 托管）
static-map = /static=/app/collected_static
static-map = /media=/app/media

# 日志
disable-logging = false
log-4xx = true
log-5xx = true