# Generated by Django 4.2.27 on 2026-01-06 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0004_alter_competition_id_alter_competitioncategory_id_and_more'),
        ('award', '0003_award_event_alter_award_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='团队名称')),
                ('applied_award_level', models.CharField(help_text='如：一等奖', max_length=50, verbose_name='申请奖项等级')),
                ('attachment', models.FileField(upload_to='temp_certs/%Y/', verbose_name='获奖证书文件')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '待审核'), ('approved', '已获奖/审核通过'), ('rejected', '驳回')], default='draft', max_length=20)),
                ('converted_award', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='award.award', verbose_name='关联的正式奖项记录')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='competitions.competitionevent')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='joined_teams', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(blank=True, related_name='guided_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
