# Generated by Django 4.2.27 on 2026-01-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='works',
            field=models.FileField(blank=True, null=True, upload_to='temp/team_works/%Y/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='temp/temp_certs/%Y/', verbose_name='获奖证书文件'),
        ),
    ]
