# Generated by Django 4.2.27 on 2026-01-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_works_alter_team_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='temp_cert_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='待核实证书编号'),
        ),
    ]
