# Generated by Django 4.2.27 on 2026-01-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_temp_cert_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='applied_award_level',
            field=models.CharField(blank=True, help_text='如：一等奖', max_length=50, null=True, verbose_name='申请奖项等级'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('event', 'leader'), name='unique_leader_per_event'),
        ),
    ]
