# Generated by Django 4.2.27 on 2026-01-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_team_applied_award_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('submitted', '已报名/待初筛'), ('shortlisted', '入围/审核通过'), ('rejected', '初筛驳回'), ('awarded', '已获奖'), ('ended', '未获奖/参赛结束')], default='draft', max_length=20),
        ),
    ]
