# Generated by Django 6.0 on 2025-12-28 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('userManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='图标')),
                ('path', models.CharField(blank=True, max_length=200, null=True, verbose_name='路由地址')),
                ('component', models.CharField(blank=True, max_length=200, null=True, verbose_name='组件路径')),
                ('permission_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='权限标识')),
                ('menu_type', models.CharField(choices=[('M', '目录'), ('C', '菜单'), ('F', '按钮')], default='M', max_length=1)),
                ('order_num', models.IntegerField(default=0, verbose_name='显示排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='userManage.menu')),
                ('roles', models.ManyToManyField(related_name='menus', to='auth.group', verbose_name='可见角色')),
            ],
            options={
                'verbose_name': '菜单管理',
                'db_table': 'sys_menu',
                'ordering': ['order_num'],
            },
        ),
    ]
