# Generated by Django 4.2.27 on 2026-01-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0003_menu_level_menu_lft_menu_rght_menu_tree_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
