# Generated by Django 4.2.27 on 2026-01-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0004_alter_menu_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
