# Generated by Django 6.0 on 2025-12-28 11:11

import certificate.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cert_no', models.CharField(max_length=100, unique=True, verbose_name='证书编号')),
                ('image_uri', models.ImageField(upload_to=certificate.models.certificate_upload_path, verbose_name='证书图片路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '证书信息',
                'db_table': 'certificate',
            },
        ),
    ]
