# Generated by Django 6.0 on 2025-12-28 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱地址')),
                ('department', models.CharField(max_length=100, verbose_name='院系')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='专业')),
                ('clazz', models.CharField(blank=True, max_length=50, null=True, verbose_name='班级')),
                ('title', models.CharField(blank=True, help_text='仅老师/管理员填写', max_length=50, null=True, verbose_name='职称')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, to_field='user_id')),
            ],
            options={
                'verbose_name': '个人档案',
                'db_table': 'sys_user_profile',
            },
        ),
    ]
