# Generated by Django 4.2.27 on 2026-01-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_profile_college_alter_profile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qq',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='QQ'),
        ),
    ]
