# Generated by Django 6.0 on 2025-12-27 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='类别名称')),
            ],
            options={
                'verbose_name': '竞赛类别',
                'db_table': 'sys_competition_category',
            },
        ),
        migrations.CreateModel(
            name='CompetitionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='级别名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='级别描述')),
            ],
            options={
                'verbose_name': '竞赛级别',
                'db_table': 'sys_competition_level',
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='竞赛名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='竞赛简介')),
                ('year', models.IntegerField(verbose_name='举办年份')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_competitions', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competitions', to='competitions.competitioncategory', verbose_name='竞赛类别')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competitions', to='competitions.competitionlevel', verbose_name='竞赛级别')),
            ],
            options={
                'verbose_name': '竞赛信息',
                'db_table': 'sys_competition',
            },
        ),
    ]
