# Generated by Django 6.0 on 2025-12-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='uri',
            field=models.CharField(default=0, max_length=8182, verbose_name='竞赛官网'),
            preserve_default=False,
        ),
    ]
