# Generated by Django 4.2.27 on 2026-01-06 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_alter_competition_id_alter_competitioncategory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='competitioncategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='competitionlevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CompetitionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='本次赛事名称')),
                ('start_time', models.DateTimeField(verbose_name='报名开始时间')),
                ('end_time', models.DateTimeField(verbose_name='报名结束时间')),
                ('status', models.CharField(choices=[('active', '进行中'), ('reviewing', '审核/评奖中'), ('archived', '已归档')], default='active', max_length=20, verbose_name='状态')),
                ('final_participants_count', models.IntegerField(default=0, verbose_name='最终参赛人数(归档后)')),
                ('final_winners_count', models.IntegerField(default=0, verbose_name='最终获奖人数(归档后)')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='competitions.competition', verbose_name='所属竞赛')),
            ],
            options={
                'verbose_name': '赛事场次',
                'db_table': 'sys_competition_event',
            },
        ),
    ]
