# Generated by Django 4.2.27 on 2026-01-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_alter_competition_id_alter_competitioncategory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='scale',
            field=models.CharField(choices=[('院级', '院级'), ('校级', '校级'), ('市级', '市级'), ('省级', '省级'), ('国家级', '国家级'), ('国际级', '国际级')], default='院级', max_length=20, verbose_name='竞赛规模'),
        ),
        migrations.AlterField(
            model_name='competitionevent',
            name='status',
            field=models.CharField(choices=[('registration', '报名中'), ('screening', '初筛中'), ('ongoing', '比赛进行中'), ('awarding', '评奖/审核中'), ('archived', '已归档')], default='active', max_length=20, verbose_name='状态'),
        ),
    ]
