# Generated by Django 4.2.27 on 2026-01-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_competition_scale_alter_competitionevent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='uri',
            field=models.CharField(blank=True, max_length=8182, null=True, verbose_name='竞赛官网'),
        ),
    ]
