# Generated by Django 4.2.27 on 2026-01-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_alter_competition_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='scale',
            field=models.CharField(choices=[('院级', '院级'), ('校级', '校级'), ('市级', '市级'), ('省级', '省级'), ('国家级', '国家级'), ('国际级', '国际级')], max_length=20, verbose_name='竞赛规模'),
        ),
    ]
